import { Table, Tbody, Td, Th, Thead, Tr } from "@/components/base-table";
import TableHeader from "@/components/base-table/TableHeader";

export default function ScoreBoardMinorFundamentalTable() {
    return (
        <>
            <TableHeader color="black" bgColor="#FFFF00" heading="MINOR FUNDAMENTAL" />
            <Table>
                <Thead bgColor="#A4C1F4">
                    <Tr>
                        <Th bgColor="#A4C1F4"></Th>
                        <Th bgColor="#A4C1F4">PMI-S</Th>
                        <Th bgColor="#A4C1F4">SCORE</Th>
                        <Th bgColor="#A4C1F4">PMI-M</Th>
                        <Th bgColor="#A4C1F4">SCORE</Th>
                        <Th bgColor="#A4C1F4">RETAIL SALES</Th>
                        <Th bgColor="#A4C1F4">SCORE</Th>
                        <Th bgColor="#A4C1F4">CHANGE</Th>
                        <Th bgColor="#A4C1F4">SCORE</Th>
                        <Th bgColor="#A4C1F4">CCI Change</Th>
                        <Th bgColor="#A4C1F4">SCORE</Th>
                        <Th bgColor="#A4C1F4">BUSINESS CONFIDENCE</Th>
                        <Th bgColor="#A4C1F4">SCORE</Th>
                        <Th bgColor="#A4C1F4">SUM</Th>
                    </Tr>
                </Thead>
                <Tbody fullBorders>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                </Tbody>
            </Table>
        </>
    );
}