import { Table, Tbody, Td, Th, Thead, Tr } from "@/components/base-table";
import TableHeader from "@/components/base-table/TableHeader";

export default function ScoreBoardFundamentalDataTable() {
    return (
        <>
            <TableHeader bgColor="#0022FF" heading="FUNDAMENTAL DATA" />
            <Table>
                <Thead bgColor="#A4C1F4">
                    <Tr>
                        <Th bgColor="#A4C1F4"></Th>
                        <Th bgColor="#A4C1F4">GDP ANNUAL</Th>
                        <Th bgColor="#A4C1F4">CHANGE</Th>
                        <Th bgColor="#A4C1F4">GDP</Th>
                        <Th bgColor="#A4C1F4">Change</Th>
                        <Th bgColor="#A4C1F4">UNEMPLOYMENT</Th>
                        <Th bgColor="#A4C1F4">Change</Th>
                        <Th bgColor="#A4C1F4">INFLATION</Th>
                        <Th bgColor="#A4C1F4">Change</Th>
                        <Th bgColor="#A4C1F4">INTEREST RATE</Th>
                        <Th bgColor="#A4C1F4">Change</Th>
                        <Th bgColor="#A4C1F4">INFLATION MOM</Th>
                        <Th bgColor="#A4C1F4">Change</Th>
                        <Th bgColor="#A4C1F4">PMI-S</Th>
                        <Th bgColor="#A4C1F4">Change</Th>
                        <Th bgColor="#A4C1F4">PMI-M</Th>
                        <Th bgColor="#A4C1F4">Change</Th>
                        <Th bgColor="#A4C1F4">RETAIL SALES</Th>
                        <Th bgColor="#A4C1F4">Change</Th>
                        <Th bgColor="#A4C1F4">CCI Change</Th>
                        <Th bgColor="#A4C1F4">Business Con</Th>
                    </Tr>
                </Thead>
                <Tbody fullBorders>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                </Tbody>
            </Table>
        </>
    );
}