import Table from "@/components/tables/Heatmap/Table";
import Tbody from "@/components/tables/Heatmap/Tbody";
import Td from "@/components/tables/Heatmap/Td";
import Th from "@/components/tables/Heatmap/Th";
import Thead from "@/components/tables/Heatmap/Thead";
import Tr from "@/components/tables/Heatmap/Tr";
import TableHeader from "@/components/tables/TableHeader";

export default function ScoreBoardFundamentalDataTable() {
    return (
        <>
            <TableHeader bgColor="#0022FF" heading="FUNDAMENTAL DATA" />
            <Table>
                <Thead bgColor="#A4C1F4">
                    <Tr>
                        <Th></Th>
                        <Th>GDP ANNUAL</Th>
                        <Th>CHANGE</Th>
                        <Th>GDP</Th>
                        <Th>Change</Th>
                        <Th>UNEMPLOYMENT</Th>
                        <Th>Change</Th>
                        <Th>INFLATION</Th>
                        <Th>Change</Th>
                        <Th>INTEREST RATE</Th>
                        <Th>Change</Th>
                        <Th>INFLATION MOM</Th>
                        <Th>Change</Th>
                        <Th>PMI-S</Th>
                        <Th>Change</Th>
                        <Th>PMI-M</Th>
                        <Th>Change</Th>
                        <Th>RETAIL SALES</Th>
                        <Th>Change</Th>
                        <Th>CCI Change</Th>
                        <Th>Business Con</Th>
                    </Tr>
                </Thead>
                <Tbody fullBorders>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                    </Tr>
                </Tbody>
            </Table>
        </>
    );
}