import Table from "@/components/base-table/Heatmap/Table";
import Tbody from "@/components/base-table/Heatmap/Tbody";
import Td from "@/components/base-table/Heatmap/Td";
import Th from "@/components/base-table/Heatmap/Th";
import Thead from "@/components/base-table/Heatmap/Thead";
import Tr from "@/components/base-table/Heatmap/Tr";
import TableHeader from "@/components/base-table/TableHeader";

export default function ScoreBoardMajorFundamentalTable() {
    return (
        <>
            <TableHeader bgColor="#12AD2B" heading="MAJOR FUNDAMENTAL" />
            <Table>
                <Thead bgColor="#A4C1F4">
                    <Tr>
                        <Th></Th>
                        <Th>GDP ANNUAL</Th>
                        <Th>SCORE</Th>
                        <Th>Change</Th>
                        <Th>SCORE</Th>
                        <Th>GDP</Th>
                        <Th>SCORE</Th>
                        <Th>GDP CHANGE</Th>
                        <Th>SCORE</Th>
                        <Th>UNEMPLOYMENT</Th>
                        <Th>SCORE</Th>
                        <Th>UNEMPLOYMENT CHANGE</Th>
                        <Th>SCORE</Th>
                        <Th>INFLATION</Th>
                        <Th>SCORE</Th>
                        <Th>INFLATION CHANGE</Th>
                        <Th>SCORE</Th>
                        <Th>NFLATION MOM</Th>
                        <Th>SCORE</Th>
                        <Th>CHANGE</Th>
                        <Th>SCORE</Th>
                        <Th>INTEREST</Th>
                        <Th>SCORE</Th>
                        <Th>INTEREST CHANGE</Th>
                        <Th>SCORE</Th>
                        <Th>SUM</Th>
                        <Th></Th>
                    </Tr>
                </Thead>
                <Tbody fullBorders>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                        <Td>-3.9</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>1.7</Td>
                        <Td>51.2</Td>
                        <Td>1.8</Td>
                        <Td>-0.9</Td>
                        <Td>-1.6</Td>
                        <Td>-3.3</Td>
                        <Td>Strong Bullish</Td>
                    </Tr>
                </Tbody>
            </Table>
        </>
    );
}