import Table from "@/components/tables/Heatmap/Table";
import Tbody from "@/components/tables/Heatmap/Tbody";
import Td from "@/components/tables/Heatmap/Td";
import Th from "@/components/tables/Heatmap/Th";
import Thead from "@/components/tables/Heatmap/Thead";
import Tr from "@/components/tables/Heatmap/Tr";
import TableHeader from "@/components/tables/TableHeader";

export default function ScoreBoardMinorFundamentalTable() {
    return (
        <>
            <TableHeader color="black" bgColor="#FFFF00" heading="MINOR FUNDAMENTAL" />
            <Table>
                <Thead bgColor="#A4C1F4">
                    <Tr>
                        <Th></Th>
                        <Th>PMI-S</Th>
                        <Th>SCORE</Th>
                        <Th>PMI-M</Th>
                        <Th>SCORE</Th>
                        <Th>RETAIL SALES</Th>
                        <Th>SCORE</Th>
                        <Th>CHANGE</Th>
                        <Th>SCORE</Th>
                        <Th>CCI Change</Th>
                        <Th>SCORE</Th>
                        <Th>BUSINESS CONFIDENCE</Th>
                        <Th>SCORE</Th>
                        <Th>SUM</Th>
                    </Tr>
                </Thead>
                <Tbody fullBorders>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                    <Tr>
                        <Td>USD</Td>
                        <Td>2.5</Td>
                        <Td>-0.2</Td>
                        <Td>2.3</Td>
                        <Td>-0.8</Td>
                        <Td>4</Td>
                        <Td>-0.1</Td>
                        <Td>3</Td>
                        <Td>0.1</Td>
                        <Td>4.5</Td>
                        <Td>-0.25</Td>
                        <Td>0.5</Td>
                        <Td>0.1</Td>
                        <Td>52.9</Td>
                    </Tr>
                </Tbody>
            </Table>
        </>
    );
}